package:
  name: falmeida-py
  version: 0.7

source:
  path: ..

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - processrcmfolder = uconnrcmpy.dataprocessing:process_folder


requirements:
  build:
    - python >=3.7,{{PY_VER}}*
    - setuptools
    - setuptools-git
    - pandas
    - tabulate
    - docopt
    - biopython

  run:
    - python {{PY_VER}}*
    - setuptools
    - setuptools-git
    - pandas
    - tabulate
    - docopt
    - biopython

channels:
  - anaconda
  - conda-forge
  - bioconda

about:
  home: https://github.com/fmalmeida/gff-toolbox
