package:
  name: falmeida-py
  version: '1.2.2'

source:
  path: ..

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - processrcmfolder = uconnrcmpy.dataprocessing:process_folder


requirements:
  build:
    - python>=3.8
    - setuptools
    - setuptools-git
    - pandas
    - tabulate
    - docopt
    - biopython
    - simplejson
    - importlib_metadata
    - pyyaml

  run:
    - python>=3.8
    - setuptools
    - setuptools-git
    - pandas
    - tabulate
    - docopt
    - biopython
    - simplejson
    - importlib_metadata
    - pyyaml

channels:
  - anaconda
  - conda-forge
  - bioconda

about:
  home: https://github.com/fmalmeida/gff-toolbox
